# Nome da aplica\u00E7\u00E3o. DEVE ser igual ao nome do arquivo no reposit\u00F3rio Git (sem o perfil).
spring.application.name=microservico-radares-bff

# Config Server
spring.config.import=optional:configserver:http://config-server:8888

# \u2705 CONFIGURA\u00C7\u00C3O IMPORTANTE:
# Se o BFF roda no Docker e o Monitoramento tamb\u00E9m: use o nome do container (ex: microservico-monitoramento:8089)
# Se o BFF roda no Docker e o Monitoramento no Windows: use http://host.docker.internal:8089
# Se ambos rodam no Windows (IDE): use http://localhost:8089
microservico.monitoramento.url=http://host.docker.internal:8089

#Ativando Virtual Threads
spring.threads.virtual.enabled=true

#Produ\u00E7\u00E3o / Docker Completo (Via Eureka) O sistema usar\u00E1 o loadBalancedRestTemplate.
#microservico.monitoramento.url=http://MICROSERVICO-MONITORAMENTO

# Keycloak JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://192.168.0.6:8180/realms/radares-realm
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://192.168.0.6:8180/realms/radares-realm/protocol/openid-connect/certs

# ALTERE o jwk-set-uri para usar 'host.docker.internal' (rota interna do Docker para o Host)
# Isso permite que o Java conecte no Keycloak sem ser bloqueado pelo Firewall/Roteamento
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://host.docker.internal:8180/realms/radares-realm/protocol/openid-connect/certs

#Configura\u00E7\u00F5es WebSocket
# Prefixo para onde os controllers recebem mensagens
spring.messages.broker.application-destination-prefix=/app
# Habilita o broker em mem\u00F3ria (como estava em WebSocketConfig)
spring.messages.broker.simple-broker.enabled=true
# Prefixo para os t\u00F3picos que os clientes ouvem
spring.messages.broker.simple-broker.prefixes=/topic,/queue

# Desabilita CORS do Spring Boot (usamos o do SecurityConfig)
# Isso evita m\u00FAltiplos headers Access-Control-Allow-Origin
spring.web.cors.enabled=false

# Logs detalhados para debug
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG
logging.level.com.coruja=DEBUG

# Configura\u00E7\u00E3o do Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
# spring.data.redis.password=  (Descomente e preencha se tiver senha)

# Desabilita filtro CORS autom\u00E1tico
management.endpoints.web.cors.allowed-origins=
management.endpoints.web.cors.allowed-methods=

# Configura\u00E7\u00F5es do Elasticsearch (Obrigat\u00F3rio para a classe ElasticsearchConfig)
# No Docker, usamos o nome do servi\u00E7o definido no docker-compose.yml
elasticsearch.host=elasticsearch
elasticsearch.port=9200