spring.application.name=microservico-radares-bff

# 1. Define o perfil de produ\u00E7\u00E3o como ativo
#spring.profiles.active=prod
# Define o perfil de dev como ativo
spring.profiles.active=dev

# A aplica\u00E7\u00E3o tentar\u00E1 buscar o config server, se falhar (optional:),
# ela continuar\u00E1 e usar\u00E1 o 'application-prod.properties' local como fallback.



